In [4]:
import os, warnings
import numpy as np
import time

import numpy as np
import pandas as pd
import pickle
import os
import warnings
warnings.filterwarnings("ignore")

import sys
sys.path.insert(0,'../../uqmodels/abench')
sys.path.insert(0,'../../n5_uqmodels/')
sys.path.insert(0,'src/')
import abench 
import uqmodels
import yaml
from functools import partial
from pathlib import Path

In [2]:
import importlib
import src.descriptor
importlib.reload(src.descriptor)

In [ ]:
# %load_ext autoreload
# %autoreload 2

In [6]:
from abench.store.data_management import explore_csv_hierarchy
metadata = explore_csv_hierarchy('data',['dataset','set'])
if(False): # Delete data to 
    for n,sample in metadata.iterrows():
        path = sample['path']
        print(path)
        data = pd.read_csv(path)
        try:
            data = data.drop(['dataset', 'set','filename', 'seqId', 'length', 'cat_length', 'cat_edge'],axis=1)
        except:
            pass
        data.to_csv(path,index=False)

In [ ]:
from abench.store.data_management import explore_csv_hierarchy,filter_metadata, augment_csvs_with_metadata
# metadata=filter_metadata(metadata,constraint_selection_list=[('dataset',dataset),('set',['new_dataset10_r1'])])
# metadata
metadata=filter_metadata(metadata,constraint_selection_list=[('dataset',['new_dataset10'])])
metadata.head(2)

# Attacks injection

In [1]:
dataset_list = ['20260615_site10']
set_list = ['dataset_r2']

In [2]:
from abench.store.data_management import explore_csv_hierarchy,filter_metadata
metadata = explore_csv_hierarchy('data',['dataset','set'])
metadata=filter_metadata(metadata,constraint_selection_list=[('dataset',dataset_list),('set',set_list)])
metadata

,dataset,set,filename,path
28,20260615_site10,dataset_r2,dataset_r2.csv,data/20260615_site10/dataset_r2/dataset_r2.csv

In [7]:
from src.perturbator import random_pos_offset,apply_perturbations

config_yaml_path = './config/config_attack.yaml'
with open(config_yaml_path) as f:
    config_attack = yaml.safe_load(f)    

with open(config_attack['template']) as f:
    config_template = yaml.safe_load(f)  

cfg_params=pd.concat([pd.DataFrame.from_dict(config_attack, orient='index'),pd.DataFrame.from_dict(config_template, orient='index')])

# ATTACK TYPE:
# random_pos_offset_low
# random_pos_offset_median
# random_pos_offset_high
# random_pos_offset_low_randomTime_delay
# random_pos_offset_low_road_constraint
dict_perturbators = {"random_pos_offset_low_randomTime_delay_back": partial(random_pos_offset,config_yaml=config_attack)}
for key,perturbators in dict_perturbators.items():
    for n,sample in metadata.iterrows():
        path = sample['path']
        df = pd.read_csv(path)
        df_perturbation = apply_perturbations(df,group_perturbation={key:perturbators},Id_col="seqId",time_col="ts")
        path = path.replace('20260615_site10','20260615_site10'+'_'+key)
        cfg_path = path.replace('csv','log')
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        cfg_params.to_csv(cfg_path,sep=':', mode='w',header=False)
        df_perturbation.to_csv(path,index=False)

print("finish")

finish

In [15]:
# Creation d'un data set perturbés.
from src.perturbator import apply_perturbations, const_pos_offset

config_yaml_path = './config/config_attack.yaml'
with open(config_yaml_path) as f:
    config_attack = yaml.safe_load(f)    

with open(config_attack['template']) as f:
    config_template = yaml.safe_load(f)  

cfg_params=pd.concat([pd.DataFrame.from_dict(config_attack, orient='index'),pd.DataFrame.from_dict(config_template, orient='index')])

# ATTACK TYPE:
# const_pos_offset_low
dict_perturbators = {"const_pos_offset_low_02": partial(const_pos_offset,config_yaml=config_attack)}
for key,perturbators in dict_perturbators.items():
    for n,sample in metadata.iterrows():
        path = sample['path']
        df = pd.read_csv(path)
        df_perturbation = apply_perturbations(df,group_perturbation={key:perturbators},Id_col="new_id_1",time_col="ts")
        path = path.replace('20260615_site10','20260615_site10'+'_'+key)
        cfg_path = path.replace('csv','log')
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        cfg_params.to_csv(cfg_path,sep=':', mode='w',header=False)
        df_perturbation.to_csv(path,index=False)

print("finish")

finish

# Add descriptors

In [2]:
from abench.store.data_management import explore_csv_hierarchy,filter_metadata
data_list = [
            # '20260615_site1',
            # '20260615_site1_const_pos_offset_low_02',
            # '20260615_site1_random_pos_offset_low_02',
            # '20260615_site1_random_pos_offset_median_02',
            # '20260615_site1_random_pos_offset_high_02',
            # '20260615_site1_random_pos_offset_low_randomTime_delay',
            # '20260615_site1_random_pos_offset_low_road_constraint',
            
            # '20260615_site10',
            '20260615_site10_const_pos_offset_low_02',
            '20260615_site10_random_pos_offset_low_02',
            '20260615_site10_random_pos_offset_median_02',
            '20260615_site10_random_pos_offset_high_02',
            # '20260615_site10_random_pos_offset_low_randomTime_delay',
            # '20260615_site10_random_pos_offset_low_road_constraint',
            ]
set_list = ['dataset_r2']
# set_list = [
# 'r2_set_0',
# 'r2_set_1',
# 'r2_set_2',
# 'r2_set_3',
# 'r2_set_4'
# ]
metadata = explore_csv_hierarchy('data',['dataset','set'])
metadata=filter_metadata(metadata,constraint_selection_list=[('dataset',data_list),('set',set_list)])
metadata

,dataset,set,filename,path
1196,20260615_site10_const_pos_offset_low_02,dataset_r2,dataset_r2.csv,data/20260615_site10_const_pos_offset_low_02/d...
1223,20260615_site10_random_pos_offset_high_02,dataset_r2,dataset_r2.csv,data/20260615_site10_random_pos_offset_high_02...
1250,20260615_site10_random_pos_offset_median_02,dataset_r2,dataset_r2.csv,data/20260615_site10_random_pos_offset_median_...
1277,20260615_site10_random_pos_offset_low_02,dataset_r2,dataset_r2.csv,data/20260615_site10_random_pos_offset_low_02/...

In [3]:
# Rajout des informations contextuelle : Metadata + Descripteur + Categorization des descripteurs
from src.descriptor import macro_id,calculate_length,add_label,mark_attack,mark_zone
from functools import partial
from abench.store.data_management import augment_csvs_with_metadata

# -----------------------------------------------------------------------------
# Quantify descrptor
# -----------------------------------------------------------------------------
enrich_params = { 
                  'macro_descriptors':{"seqId":macro_id},
                  'group_descriptors':{
                                        # "length":partial(calculate_length,x_col="positionX",y_col="positionY",time_col="ts"),
                                        # "cat_attack":partial(mark_attack,weight=0.5),
                                        # sit10:
                                        # edge: ['-60546312#1','60546311#1','-118438448#1','60546304#0','60546303#0']
                                        
                                        # site1:
                                        # edge: ['27437518','1090414504','1090414505','1090414506','1090414507','1090414509','1090414510','1151278799'] 
                                        "cat_zone":partial(mark_zone,zone=[['-60546312#1','60546311#1','-118438448#1','60546304#0','60546303#0']],col='edge')
                                        },
                #  'quantize':{ "length":('quantile',[0, 0.50, 0.75, 0.90, 1.0]),
                #            "edge":('pattern',{'-60546309': 1, '60546306': 2, '118438448': 3, '1090414517': 4, '-172341587': 5, '60546304': 6, '60546309': 7, 
                #                               '1090414515': 8, '-60546312': 9, '1090414518': 10, '60546290': 11, '172341587': 12, '60546311': 13, '60546303': 14, 
                #                               '-118438448': 15, '1090414516': 16, '60546312': 17})
                # },
                 'Id_group':"seqId",
                 'time_col':"ts"}

augment_csvs_with_metadata(metadata_df=metadata,columns_to_add=['dataset', 'set', 'filename'],enrich_params=enrich_params)

print('finish')

finish

In [ ]:
from src.descriptor import macro_id,calculate_length,add_label,mark_attack,mark_zone
from functools import partial
from abench.store.data_management import augment_csvs_with_metadata
# -----------------------------------------------------------------------------
# Quantify descrptor
# -----------------------------------------------------------------------------
enrich_params = {
                # 'macro_descriptors':{"time_aligned":time_alignement,
                #                      "neighbors":partial(calculate_neighbors,group_col="time_aligned",r=20)},
                 'group_descriptors':{
                                        # "cat_attack":partial(mark_attack,weight=0.5),
                                      "cat_zone":partial(mark_zone,zone=[['-60546312#1','60546311#1','-118438448#1','60546304#0','60546303#0']],col='edge')},
                 'Id_group':"seqId",
                 'time_col':"ts"}

augment_csvs_with_metadata(metadata_df=metadata,columns_to_add=['dataset', 'set', 'filename'],enrich_params=enrich_params)

print('finish')

finish

In [ ]:
# Creation d'un data set perturbés.
from functools import partial
from pathlib import Path
from src.perturbator import gaussian_noise_perturbator, piecewise_linear_perturbator, apply_perturbations, random_pos_offset, const_pos_offset
from abench.store.data_management import explore_csv_hierarchy,filter_metadata
import yaml
metadata = explore_csv_hierarchy('data',['dataset','set'])
metadata=filter_metadata(metadata,constraint_selection_list=[('dataset',['new_dataset1']),('set',['new_dataset1'])])
metadata

,dataset,set,filename,path
547,new_dataset1,new_dataset1,training_0_999_20260210_16:50:35.csv,data/new_dataset1/new_dataset1/training_0_999_...